[workspace]

members = [
    "a19_core",
    "a19_data_structure",
    "a19_editor",
    "a19_concurrent",
    "a19_data_persist",
    "a19_state_machine",
    "a19_messaging",
    "a19_messaging_server",
    "a19_messaging_client",
]
